org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
# KFF 5.x for 1.21.1 (2.2.20), 6.x for 1.21.9+
loader_version_range=[5,)

mod_id=create_exploded
mod_name=Create: Exploded
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.harinezumi_dev.cexploded
